name: supermarche_pos
description: SuperMarché POS v3.0 — API Edition
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP & Session
  http: ^1.1.0
  shared_preferences: ^2.2.2

  # State Management
  provider: ^6.1.2

  # Scanner
  mobile_scanner: ^5.1.1

  # PDF & Print
  pdf: ^3.10.8
  printing: ^5.12.0

  # Share
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
