name: Build APK Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'  # أو الإصدار الذي يناسبك
        channel: 'stable'
    
    - name: Create local.properties
      run: |
        echo "sdk.dir=$ANDROID_HOME" > android/local.properties
        cat android/local.properties
    
    - name: Enable AndroidX
      run: |
        echo "android.useAndroidX=true" >> android/gradle.properties
        echo "android.enableJetifier=true" >> android/gradle.properties
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build APK
      run: flutter build apk --release
